### ISSUE TITLE
Broken links in Readme

### ISSUE THREAD

**Issue by Hornwitser** [Dima-369/VMT-Editor#77]
The Official website and User Guide links in the readme leads to a 404 error page.

**Comment by Dima-369** [comment]
Oh, thanks for reporting. I'll fix them. I have recently changed my Github profile name and the links got broken.

**Comment by Dima-369** [comment]
Fixed on both `develop` and `master`.

**Comment by Dima-369** [comment]
@gortnarj I also had to fix some links inside VMT Editor, see 4f3c6c8. Maybe you can cut a new release?

Sorry for the link trouble :<
